-- ============================================================
-- SCHÉMA COMPLET — PROTOTYPE INNOVATION RESPONSABLE INR
-- À exécuter dans Supabase > SQL Editor
-- ============================================================

-- ── 1. PROFILES ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text,
  last_name text,
  address text,
  role text DEFAULT 'user_startup',
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users (id)
);

-- ── 2. PROJECTS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  public_id uuid NOT NULL DEFAULT gen_random_uuid(),
  nom_projet text,
  region text,
  description text,
  is_entreprise boolean DEFAULT false,
  nom_entreprise text,
  siren text,
  activite text,
  adresse_siege text,
  effectif text,
  date_creation date,
  dirigeant text,
  user_id uuid,
  wenr_carbon_impact double precision,
  collaborator_count bigint,
  domaine text,
  livrable text,
  couts double precision,
  type_approche text,
  main_objectifs text,
  environmental_objectifs text,
  cible_service text,
  problematique text,
  referent_profil text,
  referent_projet text,
  accompagnateur_id uuid,
  project_type text,
  audit_done boolean DEFAULT false,
  audit_upload_url text,
  charte_ia_signed boolean DEFAULT false,
  charte_nr_signed boolean DEFAULT false,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_public_id_key UNIQUE (public_id),
  CONSTRAINT projects_accompagnateur_id_fkey FOREIGN KEY (accompagnateur_id) REFERENCES public.profiles (id) ON DELETE SET NULL,
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);
CREATE INDEX IF NOT EXISTS idx_projects_accompagnateur_id ON public.projects USING btree (accompagnateur_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_public_id ON public.projects (public_id);

-- ── 3. QUESTIONS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  numero integer,
  dimension text,
  thematique text,
  intitule text,
  niveau integer,
  reponse_0 text,
  reponse_1 text,
  reponse_2 text,
  reponse_3 text,
  reponse_4 text,
  dimension_en text,
  thematique_en text,
  intitule_en text,
  reponse_0_en text,
  reponse_1_en text,
  reponse_2_en text,
  reponse_3_en text,
  reponse_4_en text,
  CONSTRAINT questions_pkey PRIMARY KEY (id)
);

-- ── 4. RESPONSES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  question_id text,
  score text,
  updated_at timestamp with time zone DEFAULT now(),
  project_id bigint,
  nom text,
  prenom text,
  adresse text,
  step_id integer,
  category text,
  CONSTRAINT responses_pkey PRIMARY KEY (id),
  CONSTRAINT responses_unique_project_step_question UNIQUE (project_id, step_id, question_id),
  CONSTRAINT responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id),
  CONSTRAINT responses_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects (id)
);

-- ── 5. PROJECT_TRAININGS ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.project_trainings (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  project_id bigint,
  user_id uuid,
  training_id text NOT NULL,
  completed boolean DEFAULT false,
  CONSTRAINT project_trainings_pkey PRIMARY KEY (id),
  CONSTRAINT project_trainings_project_id_training_id_key UNIQUE (project_id, training_id),
  CONSTRAINT project_trainings_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects (id) ON DELETE CASCADE,
  CONSTRAINT project_trainings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id)
);

-- ── 6. RESILIENCE ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.resilience (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dimension text,
  dimension_id text,
  critere text,
  description text,
  intention text,
  moyen text,
  resultat text,
  critere_en text,
  description_en text,
  intention_en text,
  moyen_en text,
  resultat_en text,
  CONSTRAINT resilience_pkey PRIMARY KEY (id)
);

-- ── 7. RESILIENCE_RESPONSES ──────────────────────────────────
CREATE TABLE IF NOT EXISTS public.resilience_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id bigint,
  critere_id text,
  score integer NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT resilience_responses_pkey PRIMARY KEY (id),
  CONSTRAINT project_critere_unique UNIQUE (project_id, critere_id),
  CONSTRAINT resilience_responses_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects (id) ON DELETE CASCADE
);

-- ── TRIGGER : création automatique du profil à l'inscription ─
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO public.profiles (id, role)
  VALUES (NEW.id, 'user_startup')
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── HELPER RLS ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- ── ACTIVER RLS ──────────────────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resilience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resilience_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_trainings ENABLE ROW LEVEL SECURITY;

-- ── POLICIES : profiles ───────────────────────────────────────
CREATE POLICY "profiles_insert_own"       ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "profiles_select_own"       ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "profiles_select_admin"     ON public.profiles FOR SELECT USING (public.is_admin());
CREATE POLICY "profiles_select_accompagnateur" ON public.profiles FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.accompagnateur_id = auth.uid() AND p.user_id = profiles.id)
);
CREATE POLICY "profiles_update_own"       ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "profiles_update_admin"     ON public.profiles FOR UPDATE USING (public.is_admin());

-- ── POLICIES : projects ───────────────────────────────────────
CREATE POLICY "projects_select_creator"        ON public.projects FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "projects_select_accompagnateur" ON public.projects FOR SELECT USING (auth.uid() = accompagnateur_id);
CREATE POLICY "projects_select_admin"          ON public.projects FOR SELECT USING (public.is_admin());
CREATE POLICY "projects_insert_authenticated"  ON public.projects FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "projects_update_creator"        ON public.projects FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "projects_update_accompagnateur" ON public.projects FOR UPDATE USING (auth.uid() = accompagnateur_id);
CREATE POLICY "projects_update_admin"          ON public.projects FOR UPDATE USING (public.is_admin());
CREATE POLICY "projects_delete_admin"          ON public.projects FOR DELETE USING (public.is_admin());

-- ── POLICIES : responses ─────────────────────────────────────
CREATE POLICY "responses_select_creator"        ON public.responses FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "responses_select_accompagnateur" ON public.responses FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = responses.project_id AND p.accompagnateur_id = auth.uid())
);
CREATE POLICY "responses_select_admin"  ON public.responses FOR SELECT USING (public.is_admin());
CREATE POLICY "responses_insert_creator" ON public.responses FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "responses_update_creator" ON public.responses FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "responses_delete_creator" ON public.responses FOR DELETE USING (auth.uid() = user_id);

-- ── POLICIES : resilience_responses ─────────────────────────
CREATE POLICY "rr_select_creator" ON public.resilience_responses FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = resilience_responses.project_id AND p.user_id = auth.uid())
);
CREATE POLICY "rr_select_accompagnateur" ON public.resilience_responses FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = resilience_responses.project_id AND p.accompagnateur_id = auth.uid())
);
CREATE POLICY "rr_select_admin"  ON public.resilience_responses FOR SELECT USING (public.is_admin());
CREATE POLICY "rr_insert_creator" ON public.resilience_responses FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = resilience_responses.project_id AND p.user_id = auth.uid())
);
CREATE POLICY "rr_update_creator" ON public.resilience_responses FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = resilience_responses.project_id AND p.user_id = auth.uid())
);
CREATE POLICY "rr_delete_creator" ON public.resilience_responses FOR DELETE USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = resilience_responses.project_id AND p.user_id = auth.uid())
);

-- ── POLICIES : project_trainings ─────────────────────────────
CREATE POLICY "pt_select_creator"        ON public.project_trainings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "pt_select_accompagnateur" ON public.project_trainings FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.projects p WHERE p.id = project_trainings.project_id AND p.accompagnateur_id = auth.uid())
);
CREATE POLICY "pt_select_admin"   ON public.project_trainings FOR SELECT USING (public.is_admin());
CREATE POLICY "pt_insert_creator" ON public.project_trainings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "pt_update_creator" ON public.project_trainings FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "pt_delete_creator" ON public.project_trainings FOR DELETE USING (auth.uid() = user_id);

-- ── POLICIES : questions & resilience (référentiels) ─────────
CREATE POLICY "questions_select_authenticated" ON public.questions FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "resilience_select_authenticated" ON public.resilience FOR SELECT USING (auth.uid() IS NOT NULL);

-- ── STORAGE : bucket audit_uploads ───────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('audit_uploads', 'audit_uploads', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "audit_upload_insert" ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'audit_uploads' AND auth.uid() IS NOT NULL);
CREATE POLICY "audit_upload_select" ON storage.objects FOR SELECT
  USING (bucket_id = 'audit_uploads' AND auth.uid() IS NOT NULL);

-- ============================================================
-- FIN DU SCHÉMA
-- ============================================================